name: CI pipeline

on:
  push:
    branches:
      - "**" # matches every branch

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: checkout
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"

      - name: install dependencies
        run:
          - pip install isort
          - pip install flake8

      - name: Running isort, flake8 and tests.
        run:
          - isort --check-only  .
          - flake8 .
